import type { LucideIcon } from "lucide-react";
import {
  BadgeCheck,
  Building,
  Calendar,
  CircleCheckBig,
  ClipboardList,
  Clock,
  CreditCard,
  FileText,
  Flag,
  Gift,
  Headphones,
  Highlighter,
  Layers,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  PackageCheck,
  Palette,
  PenTool,
  Phone,
  Printer,
  Quote,
  Send,
  ShieldCheck,
  Shirt,
  Sparkles,
  Star,
  Sticker,
  Timer,
  TrendingUp,
  Truck,
  Wallet,
  X,
  Zap,
} from "lucide-react";

/** Keys are lower-case so `getIcon("badgeCheck")` and `getIcon("BadgeCheck")` both work. */
const map: Record<string, LucideIcon> = {
  badgecheck: BadgeCheck,
  building: Building,
  calendar: Calendar,
  checkcircle: CircleCheckBig,
  clipboardlist: ClipboardList,
  clock: Clock,
  creditcard: CreditCard,
  filetext: FileText,
  flag: Flag,
  gift: Gift,
  headphones: Headphones,
  highlighter: Highlighter,
  layers: Layers,
  mail: Mail,
  mappin: MapPin,
  menu: Menu,
  messagecircle: MessageCircle,
  packagecheck: PackageCheck,
  palette: Palette,
  pentool: PenTool,
  phone: Phone,
  printer: Printer,
  quote: Quote,
  send: Send,
  shieldcheck: ShieldCheck,
  shirt: Shirt,
  sparkles: Sparkles,
  star: Star,
  sticker: Sticker,
  timer: Timer,
  trendingup: TrendingUp,
  truck: Truck,
  wallet: Wallet,
  x: X,
  zap: Zap,
};

export function getIcon(name: string): LucideIcon {
  return map[name.toLowerCase()] ?? Sparkles;
}
